id: 1d252e7bd6f44269a1e959d07f8ec7ab
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_730-Dh%C4%81ra%E1%B9%87%C4%AB_T%C4%81r%C4%81%E2%80%99s_Own_Promise-v2.bo.en
  language: en
  author: ''
  volume: {}
